# =========================
# Build stage
# =========================
FROM node:22-alpine AS build
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build

# =========================
# Runtime stage
# =========================
FROM nginx:alpine

# Clean default nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy Angular dist
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

# Default nginx CMD
CMD ["nginx", "-g", "daemon off;"]
