# =========================
# Build stage
# =========================
FROM node:22-alpine AS build
WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm ci

# Copiar código y build
COPY . .
RUN npm run build

# =========================
# Runtime stage
# =========================
FROM nginx:alpine

# Limpiar contenido por defecto
RUN rm -rf /usr/share/nginx/html/*

# ✅ COPIAMOS LA RUTA CORRECTA DEL BUILD (browser)
COPY --from=build /app/dist/task-web/browser/ /usr/share/nginx/html/

# Configuración nginx para SPA
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
