name: Container Publish (GHCR)

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # Nombre de imágenes (en minúsculas para GHCR). Cambia si quieres otros nombres.
  IMAGE_BACKEND: taskapi
  IMAGE_FRONTEND: taskweb

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # GHCR requiere owner en minúsculas (por ejemplo Marco0705 -> marco0705)
      - name: Compute image base
        id: vars
        shell: bash
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          echo "OWNER_LC=$OWNER_LC" >> $GITHUB_ENV
          echo "IMAGE_BACKEND_FULL=${{ env.REGISTRY }}/$OWNER_LC/${{ env.IMAGE_BACKEND }}" >> $GITHUB_ENV
          echo "IMAGE_FRONTEND_FULL=${{ env.REGISTRY }}/$OWNER_LC/${{ env.IMAGE_FRONTEND }}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------------------------
      # BACKEND
      # -------------------------
      - name: Metadata (backend)
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_BACKEND_FULL }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag

      - name: Build & push (backend)
        uses: docker/build-push-action@v6
        with:
          context: app/backend/TaskApi
          file: app/backend/TaskApi/Containerfile
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      # -------------------------
      # FRONTEND
      # -------------------------
      - name: Metadata (frontend)
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_FRONTEND_FULL }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag

      - name: Build & push (frontend)
        uses: docker/build-push-action@v6
        with:
          context: app/frontend/task-web
          file: app/frontend/task-web/Containerfile
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}